[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Zlib",
    "CC0-1.0",
    "BSL-1.0",
    "MPL-2.0",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
version = 2
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
